name: Deploy Via FTP
on:
  push:
    branches:
      - main
      - staging
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ github.ref == 'refs/heads/main' && secrets.FTP_USERNAME || secrets.STAGING_FTP_USERNAME }}
        password: ${{ github.ref == 'refs/heads/main' && secrets.FTP_PASSWORD || secrets.STAGING_FTP_PASSWORD }}
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*
          **/.github*/**
          **/node_modules/**
    - name: Rename htaccess Go Live
      shell: python
      run: |
        import ftplib
        server = "${{ secrets.FTP_SERVER }}"
        username = "${{ github.ref == 'refs/heads/main' && secrets.FTP_USERNAME || secrets.STAGING_FTP_USERNAME }}"
        password = "${{ github.ref == 'refs/heads/main' && secrets.FTP_PASSWORD || secrets.STAGING_FTP_PASSWORD }}"
        ftp = ftplib.FTP(server)
        ftp.login(username, password)
        ftp.quit()
